version: '3'
services:

  namenode:
    image: shwsun/nn
    container_name: namenode
    hostname: namenode
    volumes:
      - /hdfs/namenode:/hdfs/name
    environment:
      - CLUSTER_NAME=hive
    ports:
      - "50070:50070"
      - "8088:8088"
      - "9870:9870"
      - "19888:19888"
    tty: true

  dn01:
    image: shwsun/dn
    container_name: dn01
    hostname: dn01
    volumes:
      - /hdfs/dn01:/hdfs/data
    depends_on:
      - namenode
    ports:
      - "8042:8042"
    #   - "50075:50075"
    tty: true

  dn02:
    image: shwsun/dn
    container_name: dn02
    hostname: dn02
    volumes:
      - /hdfs/dn02:/hdfs/data
    depends_on:
      - namenode
    ports:
      - "8043:8042"
    #   - "50075:50075"
    tty: true

  dn03:
    image: shwsun/dn
    container_name: dn03
    hostname: dn03
    volumes:
      - /hdfs/dn03:/hdfs/data
    depends_on:
      - namenode
    ports:
      - "8044:8042"
    #   - "50075:50075"
    tty: true

  rdb:
    image: shwsun/mysql-hue
    container_name: rdb
    hostname: rdb
    # volumes:
    #   - /hdfs/dn03:/hdfs/data
    # depends_on:
    #   - namenode
    # ports:
    #   - "8044:8042"
    # #   - "50075:50075"
    tty: true