version: '3'
services:

  namenode:
    image: shwsun/hive-spark
    container_name: namenode
    hostname: namenode
    volumes:
      - /hdfs/namenode:/hdfs/node
    environment:
      - CLUSTER_NAME=hive
    ports:
      - "50070:50070"
      - "8088:8088"
      - "9870:9870"
      - "19888:19888"
    tty: true

  dn01:
    image: shwsun/hive-spark
    container_name: dn01
    hostname: dn01
    volumes:
      - /hdfs/dn01:/hdfs/node
    depends_on:
      - namenode
    ports:
      - "8042:8042"
    #   - "50075:50075"
    tty: true

  dn02:
    image: shwsun/hive-spark
    container_name: dn02
    hostname: dn02
    volumes:
      - /hdfs/dn02:/hdfs/node
    depends_on:
      - namenode
    ports:
      - "8043:8042"
    #   - "50075:50075"
    tty: true

  dn03:
    image: shwsun/hive-spark
    container_name: dn03
    hostname: dn03
    volumes:
      - /hdfs/dn03:/hdfs/node
    depends_on:
      - namenode
    ports:
      - "8044:8042"
    #   - "50075:50075"
    tty: true

  rdb:
    image: shwsun/mysql-hue
    container_name: rdb
    hostname: rdb
    # volumes:
    #   - /hdfs/dn03:/hdfs/data
    # depends_on:
    #   - dn03
    # ports:
    #   - "8044:8042"
    # #   - "50075:50075"
    tty: true

  # hue:
  #   image: shwsun/hue
  #   container_name: hue
  #   hostname: hue
  #   #restart: on-failure
  #   command: bash -c "sleep 5;./startup.sh"
  #   depends_on:
  #     - "rdb"
  #   ports:
  #     - "8890:8888"
  #   tty: true